apiVersion: v2
name: shop-umbrella-blue-green
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: quarkus-helm-discounts
    version: 0.1.0
    alias: discounts
    tags:
      - discounts

  - name: quarkus-helm-products
    version: 0.1.0
    alias: products
    tags:
      - products
